.Dd April 17, 2021
.Dt MORSE 1
.Os
.Sh NAME
.Nm morse
.Nd generate and parse morse code encoded as dots and dashes
.Sh SYNOPSIS
.Nm
.Op Fl d
.Sh DESCRIPTION
Reads text from standard input,
outputs dots and dashes on standard output.
The
.Fl d
flag
.Pq Em decode
reverses the process.
.Pp
Un-encodable or un-decodable input is skipped.
Words in morse are separated with newlines.
.Sh EXAMPLES
Encode a string:
.Bd -literal -offset Ds
$ echo 'Hello, World! What a day to be alive.' | morse
\&.... . .-.. .-.. ---
\&.-- --- .-. .-.. -..
\&.-- .... .- -
\&.-
-.. .- -.--
- ---
-... .
\&.- .-.. .. ...- .
.Ed
.Pp
Enocode a string to a file, then decode it:
.Bd -literal -offset Ds
$ echo 'Hello, World! What a day to be alive.' | morse >msg.txt
$ morse -d <msg.txt
HELLO WORLD WHAT A DAY TO BE ALIVE
.Ed
.Sh AUTHORS
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl
