.Dd April 17, 2021
.Dt MORSE-PWMPLAY 1
.Os
.Sh NAME
.Nm morse-pwmplay
.Nd output morse on a passive buzzer with PWM
.Sh SYNOPSIS
.Nm
.Op Ar chip Op Ar channel
.Sh DESCRIPTION
Reads dots, dashes, spaces and newlines
.Pq as word separators
from standard input
and interfaces with
.Pa /sys/calss/pwm/pwmchipN/pwmN .
Other input characters are ignored.
The chip and channel numbers default to 0.
The dot length is fixed at 50 ms.
.Sh EXAMPLES
Play 'HELLO WORLD':
.Bd -literal -offset Ds
$ echo '.... . .-.. .-.. ---
\&.-- --- .-. .-.. -..' | morse-pwmplay
.Ed
.Pp
Do the same with
.Xr morse 1 :
$ echo 'Hello, World!' | morse | morse-pwmplay
.Ed
.Sh SEE ALSO
.Xr morse 1
.Sh AUTHORS
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl
